
# Theme
theme = "hugo-tufte"

baseURL = "https://hisam.dev"

# Basic metadata
title = "Hisam Fahri"
author = "Hisam Fahri"
languageCode = "en-US"
canonifyurls = true

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# markup stuff
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    guessSyntax = true

[params]
  subtitle = "My personal thoughts, experiences, and discoveries"
  favicon = "https://fav.farm/ðŸ¦‰"
  touchicon = "https://fav.farm/ðŸ¦‰"
  codeblocksdark = false
  marginNoteInd = "âŠ•"
  showPoweredBy = false
  hidedate = false
  showSummary = true
  math = true
  KaTeXVersion = "0.16.4"
  KaTeXCDN = "//cdn.jsdelivr.net/npm"
  sansSubtitle = false
  centerArticle = false
  copyright = "Â© 2026 Hisam Fahri"

[menu]
  [[menu.nav]]
    name = "Home"
    weight = -110
    identifier = "home"
    url = "/"
  [[menu.nav]]
    name = "Journals"
    weight = -100
    identifier = "journals"
    url = "/journals/"
