[build.environment]
DART_SASS_VERSION = "1.93.3"
GO_VERSION = "1.25.1"
HUGO_VERSION = "0.150.0"
NODE_VERSION = "22.18.0"
TZ = "Europe/Oslo"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH="$PWD/dart-sass:$PATH" && \
  hugo --gc --minify
  """
